# Generated by Django 4.2.2 on 2023-07-01 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 7XXXXXXXXXX', regex='^7[0-9]{10}$')])),
                ('mobile_operator_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(997)])),
                ('tag', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('text_message', models.TextField()),
                ('client_filter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('F', 'Failed'), ('P', 'Pending')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.client')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.dispatch')),
            ],
        ),
    ]
