# Generated by Django 4.2.3 on 2023-09-06 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='dispatch',
            name='client_filter_mobile_operator_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(997)]),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='client_filter_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='client_filter',
            field=models.IntegerField(choices=[(1, 'Tag filter'), (2, 'Mobile operator code filter')], null=True),
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time'),
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client_filter', 1), ('client_filter_mobile_operator_code__isnull', True), ('client_filter_tag__isnull', False)), models.Q(('client_filter', 2), ('client_filter_mobile_operator_code__isnull', False), ('client_filter_tag__isnull', True)), _connector='OR'), name='dispatch_client_filter_check'),
        ),
    ]
