# Generated by Django 4.2.3 on 2023-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_dispatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('F', 'Failed'), ('P', 'Pending')], db_index=True, default='P', max_length=255),
        ),
    ]
