# Generated by Django 4.2.7 on 2023-11-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_message_sending_time_alter_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['creation_time', 'sending_time']},
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('status', 'S'), ('sending_time__isnull', True), _connector='OR'), name='sending_time_with_status_sent'),
        ),
    ]
